#!/bin/bash

set -x

### Add TouchEgg launcher to autostart

xdg_autostart_path='/etc/xdg/autostart'

rm $xdg_autostart_path/touchegg.desktop || true

touch $xdg_autostart_path/touchegg.desktop

>> $xdg_autostart_path/touchegg.desktop printf "%s\n" \
	'[Desktop Entry]' \
	'Comment=' \
	'Exec=touchegg-autostart' \
	'GenericName=' \
	'Icon=preferences-desktop' \
	'MimeType=' \
	'Name=touchegg-autostart' \
	'Path=' \
	'StartupNotify=true' \
	'Terminal=false' \
	'TerminalOptions=' \
	'Type=Application' \
	'X-DBUS-ServiceName=' \
	'X-DBUS-StartupType=' \
	'X-DBUS-SubstitueUID=false' \
	'X-DBUS-Username=' \
	''

exit 0
